M48
; DRILL file {KiCad 8.0.1} date 2024-03-27T11:30:36-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-27T11:30:36-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X5.213Y-3.58
X5.213Y-4.03
X7.95Y-3.935
X7.95Y-4.335
X7.95Y-4.565
X7.95Y-4.965
M30
